development:
  adapter: postgresql
  encoding: unicode
  database: jakd_development
  pool: 5
  host: localhost
  username: postgres
  password: 1234

production:
  adapter: postgresql
  encoding: unicode
  database: jakd_production
  pool: 5
  host: localhost
  username: postgres
  password: 1234